package com.zrquan.mobile.model;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "locations")
public class Location {
    // id is generated by the database and set on the object auto magically
    @DatabaseField(generatedId = true)
    int id;
    @DatabaseField
    String name;
    @DatabaseField
    int region_id;

    Location() {
        // needed by ormlite
    }

    public String getName() {
        return name;
    }

    public int getRegionId() {
        return region_id;
    }

    public int getId() {
        return id;
    }
}
