package com.zrquan.mobile.support.em;

//与return_code.rb定义一致
public enum ServerCode {
    //GENERAL
    S_OK,
    FA_UNKNOWN_ERROR,
    FA_INVALID_PARAMETERS,
    FA_NOT_SUPPORTED_PARAMETERS,
    FA_INNER_NET_CONNECT_ERROR,
    FA_WRITING_TO_DATABASE_ERROR,

    //RESTFUL相关
    FA_RESOURCE_ALREADY_EXIST,
    FA_RESOURCE_NOT_EXIST,

    //用户相关
    FA_INVALID_MOBILE_FORMAT,
    FA_USER_ALREADY_EXIT,
    FA_USER_NOT_EXIT,
    FA_NEED_VERIFY_CODE,
    FA_INVALID_VERIFY_CODE,
    FA_VERIFY_CODE_EXPIRED,
    FA_INVALID_USER_NAME_FORMAT,
    FA_INVALID_PASSWORD_FORMAT,
    FA_PASSWORD_ERROR,
    FA_ACCESS_TOKEN_NOT_EXIT,
    FA_JWT_SIGNATURE_ERROR,
    FA_SIGN_IN_TIME_INCONSISTENT,
    FA_SIGN_IN_TIME_EXPIRED,
    FA_UNAUTHORIZED,

    //关注
    FA_SELF_RELATIONSHIP_ERROR,
    FA_RELATIONSHIP_ALREADY_EXIT,
    FA_RELATIONSHIP_NOT_EXIT,

    //问答存草稿
    FA_QUESTION_ALREADY_ANSWERED
}
