package com.zrquan.mobile.modal;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "regions")
public class Region {
    // id is generated by the database and set on the object auto magically
    @DatabaseField(generatedId = true)
    int id;
    @DatabaseField
    String name;

    Region() {
        // needed by ormlite
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }
}
